/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Map;

import javax.swing.JOptionPane;

/**
 *
 * @author yamis
 */
public class Filter extends javax.swing.JFrame {

    private boolean[] state = new boolean[13];
    double radius;
    private final MapsViewer mapviewf;
    
    public Filter(MapsViewer mapview) {
        initComponents();
        mapviewf = mapview;
        for (int i = 0; i < 12; i++)
        {
            state[i] = true;
        }
    }

    private Filter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiusGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        katokBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        yogaBox = new javax.swing.JCheckBox();
        fitnesBox = new javax.swing.JCheckBox();
        swimBox = new javax.swing.JCheckBox();
        dzudoBox = new javax.swing.JCheckBox();
        fightBox = new javax.swing.JCheckBox();
        xokeyBox = new javax.swing.JCheckBox();
        zalBox = new javax.swing.JCheckBox();
        tekvondoBox = new javax.swing.JCheckBox();
        volleybalBox = new javax.swing.JCheckBox();
        lightBox = new javax.swing.JCheckBox();
        futtbolBox = new javax.swing.JCheckBox();
        boksBox = new javax.swing.JCheckBox();
        jRadioButton500metr = new javax.swing.JRadioButton();
        jRadioButton1km = new javax.swing.JRadioButton();
        jRadioButton5km = new javax.swing.JRadioButton();
        jRadioButton2km = new javax.swing.JRadioButton();
        jRadioButtonall = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        allCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Выбрать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        katokBox.setSelected(true);
        katokBox.setText("Каток");
        katokBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                katokBoxStateChanged(evt);
            }
        });
        katokBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katokBoxActionPerformed(evt);
            }
        });

        jButton2.setText("Отмена");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        yogaBox.setSelected(true);
        yogaBox.setText("Йога");
        yogaBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yogaBoxStateChanged(evt);
            }
        });
        yogaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogaBoxActionPerformed(evt);
            }
        });

        fitnesBox.setSelected(true);
        fitnesBox.setText("Фитнес");
        fitnesBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fitnesBoxStateChanged(evt);
            }
        });
        fitnesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnesBoxActionPerformed(evt);
            }
        });

        swimBox.setSelected(true);
        swimBox.setText("Бассейн");
        swimBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                swimBoxStateChanged(evt);
            }
        });
        swimBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swimBoxActionPerformed(evt);
            }
        });

        dzudoBox.setSelected(true);
        dzudoBox.setText("Дзюдо");
        dzudoBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dzudoBoxStateChanged(evt);
            }
        });
        dzudoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzudoBoxActionPerformed(evt);
            }
        });

        fightBox.setSelected(true);
        fightBox.setText("Борьба");
        fightBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fightBoxStateChanged(evt);
            }
        });
        fightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightBoxActionPerformed(evt);
            }
        });

        xokeyBox.setSelected(true);
        xokeyBox.setText("Хоккей");
        xokeyBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xokeyBoxStateChanged(evt);
            }
        });
        xokeyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xokeyBoxActionPerformed(evt);
            }
        });

        zalBox.setSelected(true);
        zalBox.setText("Тренажерный зал");
        zalBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zalBoxStateChanged(evt);
            }
        });
        zalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalBoxActionPerformed(evt);
            }
        });

        tekvondoBox.setSelected(true);
        tekvondoBox.setText("Тхэквондо");
        tekvondoBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tekvondoBoxStateChanged(evt);
            }
        });
        tekvondoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekvondoBoxActionPerformed(evt);
            }
        });

        volleybalBox.setSelected(true);
        volleybalBox.setText("Воллейбол");
        volleybalBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volleybalBoxStateChanged(evt);
            }
        });
        volleybalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volleybalBoxActionPerformed(evt);
            }
        });

        lightBox.setSelected(true);
        lightBox.setText("Легкая атлетика");
        lightBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lightBoxStateChanged(evt);
            }
        });
        lightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightBoxActionPerformed(evt);
            }
        });

        futtbolBox.setSelected(true);
        futtbolBox.setText("Футбол");
        futtbolBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                futtbolBoxStateChanged(evt);
            }
        });
        futtbolBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futtbolBoxActionPerformed(evt);
            }
        });

        boksBox.setSelected(true);
        boksBox.setText("Бокс");
        boksBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boksBoxStateChanged(evt);
            }
        });
        boksBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boksBoxActionPerformed(evt);
            }
        });

        radiusGroup.add(jRadioButton500metr);
        jRadioButton500metr.setText("500 метров");
        jRadioButton500metr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton500metrActionPerformed(evt);
            }
        });

        radiusGroup.add(jRadioButton1km);
        jRadioButton1km.setText("1 километр");

        radiusGroup.add(jRadioButton5km);
        jRadioButton5km.setText("5 километров");
        jRadioButton5km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5kmActionPerformed(evt);
            }
        });

        radiusGroup.add(jRadioButton2km);
        jRadioButton2km.setText("2 километра");

        radiusGroup.add(jRadioButtonall);
        jRadioButtonall.setSelected(true);
        jRadioButtonall.setText("Любое растояние");
        jRadioButtonall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonallActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Растояние:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Категория:");

        allCheckBox.setSelected(true);
        allCheckBox.setText("Выбрать все категории");
        allCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yogaBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(xokeyBox)
                                            .addComponent(fightBox)
                                            .addComponent(volleybalBox)
                                            .addComponent(lightBox)
                                            .addComponent(futtbolBox)
                                            .addComponent(zalBox)
                                            .addComponent(fitnesBox)
                                            .addComponent(swimBox)
                                            .addComponent(boksBox)
                                            .addComponent(tekvondoBox)
                                            .addComponent(dzudoBox))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(katokBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addComponent(allCheckBox)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton500metr)
                                    .addComponent(jRadioButton5km)
                                    .addComponent(jRadioButtonall)
                                    .addComponent(jRadioButton2km)
                                    .addComponent(jRadioButton1km)
                                    .addComponent(jLabel1))
                                .addGap(78, 78, 78))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(katokBox)
                            .addComponent(allCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yogaBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fitnesBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zalBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xokeyBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fightBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boksBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dzudoBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(futtbolBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volleybalBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tekvondoBox)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton500metr)
                                .addGap(26, 26, 26))
                            .addComponent(jRadioButton1km))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2km)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5km)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mapviewf.removeAllMarkers();
        mapviewf.addMarkerUser();
        for (int i = 0; i < 12; i++)
        {
            if (state[i]) {
                
                mapviewf.loadMarkerFromDbId(i+1);
                
            }
        }
        
        if (jRadioButton500metr.isSelected()) {
            radius = 0.5;
        } else if (jRadioButton1km.isSelected()) {
            radius = 1;
        } else if (jRadioButton2km.isSelected()) {
            radius = 2;
        } else if (jRadioButton5km.isSelected()) {
            radius = 5;
        }
         else
            radius = 100000;
        
        mapviewf.checkRadiusMarker(radius);
        mapviewf.addMarkersToMap();
        mapviewf.addMarkersOnMap();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void katokBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katokBoxActionPerformed
        if(!state[0])
            state[0]= true;
        else state[0] = false;
    }//GEN-LAST:event_katokBoxActionPerformed

    private void katokBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_katokBoxStateChanged
        
    }//GEN-LAST:event_katokBoxStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void yogaBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yogaBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_yogaBoxStateChanged

    private void yogaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogaBoxActionPerformed
        if(!state[1])
            state[1]= true;
        else state[1] = false;
    }//GEN-LAST:event_yogaBoxActionPerformed

    private void fitnesBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fitnesBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fitnesBoxStateChanged

    private void fitnesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnesBoxActionPerformed
        if(!state[2])
            state[2]= true;
        else state[2] = false;
    }//GEN-LAST:event_fitnesBoxActionPerformed

    private void swimBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_swimBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_swimBoxStateChanged

    private void swimBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swimBoxActionPerformed
        if(!state[3])
            state[3]= true;
        else state[3] = false;
    }//GEN-LAST:event_swimBoxActionPerformed

    private void dzudoBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dzudoBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dzudoBoxStateChanged

    private void dzudoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzudoBoxActionPerformed
        if(!state[8])
            state[8]= true;
        else state[8] = false;
    }//GEN-LAST:event_dzudoBoxActionPerformed

    private void fightBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fightBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fightBoxStateChanged

    private void fightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightBoxActionPerformed
        if(!state[6])
            state[6]= true;
        else state[6] = false;
    }//GEN-LAST:event_fightBoxActionPerformed

    private void xokeyBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xokeyBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_xokeyBoxStateChanged

    private void xokeyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xokeyBoxActionPerformed
        if(!state[5])
            state[5]= true;
        else state[5] = false;
    }//GEN-LAST:event_xokeyBoxActionPerformed

    private void zalBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zalBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_zalBoxStateChanged

    private void zalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalBoxActionPerformed
        if(!state[4])
            state[4]= true;
        else state[4] = false;
    }//GEN-LAST:event_zalBoxActionPerformed

    private void tekvondoBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tekvondoBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tekvondoBoxStateChanged

    private void tekvondoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekvondoBoxActionPerformed
        if(!state[12])
            state[12]= true;
        else state[12] = false;
    }//GEN-LAST:event_tekvondoBoxActionPerformed

    private void volleybalBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volleybalBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_volleybalBoxStateChanged

    private void volleybalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volleybalBoxActionPerformed
        if(!state[11])
            state[11]= true;
        else state[11] = false;
    }//GEN-LAST:event_volleybalBoxActionPerformed

    private void lightBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lightBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lightBoxStateChanged

    private void lightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightBoxActionPerformed
        if(!state[10])
            state[10]= true;
        else state[10] = false;
    }//GEN-LAST:event_lightBoxActionPerformed

    private void futtbolBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_futtbolBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_futtbolBoxStateChanged

    private void futtbolBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futtbolBoxActionPerformed
        if(!state[9])
            state[9]= true;
        else state[9] = false;
    }//GEN-LAST:event_futtbolBoxActionPerformed

    private void boksBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boksBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_boksBoxStateChanged

    private void boksBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boksBoxActionPerformed
        if(!state[7])
            state[7]= true;
        else state[7] = false;
    }//GEN-LAST:event_boksBoxActionPerformed

    private void jRadioButton500metrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton500metrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton500metrActionPerformed

    private void jRadioButton5kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5kmActionPerformed

    private void jRadioButtonallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonallActionPerformed

    private void allCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCheckBoxActionPerformed
        if (!allCheckBox.isSelected())
        {
            katokBox.setSelected(false);
            yogaBox.setSelected(false);
            fitnesBox.setSelected(false);
            swimBox.setSelected(false);
            zalBox.setSelected(false);
            xokeyBox.setSelected(false);
            fightBox.setSelected(false);
            boksBox.setSelected(false);
            dzudoBox.setSelected(false);
            futtbolBox.setSelected(false);
            lightBox.setSelected(false);
            volleybalBox.setSelected(false);
            tekvondoBox.setSelected(false);
            for (int i = 0; i < 12; i++) state[i] = false;
        }
        else 
        {
            katokBox.setSelected(true);
            yogaBox.setSelected(true);
            fitnesBox.setSelected(true);
            swimBox.setSelected(true);
            zalBox.setSelected(true);
            xokeyBox.setSelected(true);
            fightBox.setSelected(true);
            boksBox.setSelected(true);
            dzudoBox.setSelected(true);
            futtbolBox.setSelected(true);
            lightBox.setSelected(true);
            volleybalBox.setSelected(true);
            tekvondoBox.setSelected(true);
            for (int i = 0; i < 12; i++) state[i] = true;
        }
    }//GEN-LAST:event_allCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allCheckBox;
    private javax.swing.JCheckBox boksBox;
    private javax.swing.JCheckBox dzudoBox;
    private javax.swing.JCheckBox fightBox;
    private javax.swing.JCheckBox fitnesBox;
    private javax.swing.JCheckBox futtbolBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1km;
    private javax.swing.JRadioButton jRadioButton2km;
    private javax.swing.JRadioButton jRadioButton500metr;
    private javax.swing.JRadioButton jRadioButton5km;
    private javax.swing.JRadioButton jRadioButtonall;
    private javax.swing.JCheckBox katokBox;
    private javax.swing.JCheckBox lightBox;
    private javax.swing.ButtonGroup radiusGroup;
    private javax.swing.JCheckBox swimBox;
    private javax.swing.JCheckBox tekvondoBox;
    private javax.swing.JCheckBox volleybalBox;
    private javax.swing.JCheckBox xokeyBox;
    private javax.swing.JCheckBox yogaBox;
    private javax.swing.JCheckBox zalBox;
    // End of variables declaration//GEN-END:variables
}
